## 기본 문제 (1~10)
1. numpy를 사용하여 [10, 20, 30, 40, 50] 배열을 생성하고 출력하는 코드를 작성하세요.
2. 2x3 크기의 배열을 만들고 모든 요소가 0으로 채워지도록 작성하세요.
3. 3x3 크기의 배열을 만들고 모든 요소가 1로 채워지도록 작성하세요.
4. 1부터 20까지의 연속된 숫자로 배열을 생성하는 코드를 작성하세요.
5. 0부터 10까지 5개의 균등한 간격을 갖는 숫자로 배열을 생성하세요.
6. 3x3 크기의 난수 배열을 생성하고 출력하는 코드를 작성하세요. (0~1 사이)
7. np.array([5, 10, 15]) 배열의 모든 요소를 3배 하는 코드를 작성하세요.
8. np.array([2, 4, 6, 8, 10])에서 최대값과 최소값을 구하세요.
9. np.array([10, 20, 30, 40]) 배열을 2x2 형태로 변경하세요.
10. np.array([10, 20, 30, 40, 50])에서 20보다 큰 값만 선택하는 코드를 작성하세요.

In [2]:
import numpy as np
arr1 = np.array([10,20,30,40,50])
print(arr1)

[10 20 30 40 50]


In [3]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [7]:
np.arange(1, 11, 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

np.linspace(0, 10, 5)

In [15]:
arr2 = np.random.normal(0,1,(3,3))
print(arr2)

[[ 0.3329489   1.10456696 -2.98830002]
 [-0.24932324  0.03981514 -0.80161684]
 [-0.37756852 -0.06151685 -0.36318762]]


In [21]:
arr4 = np.array([5, 10, 15])
result = arr4 * 3
print(result)

[15 30 45]


In [18]:
arr3 = np.array([2,4,6,8,10])
print(np.min(arr3))
print(np.max(arr3))

2
10


In [20]:
arr4 = np.array([10, 20, 30, 40])
print(arr4)

[10 20 30 40]


In [23]:
x = np.array([10, 20, 30, 40])
x.reshape(2,2)

array([[10, 20],
       [30, 40]])

In [26]:
arr5 = np.array([10, 20, 30, 40, 50])
arr5[arr5 > 20]

array([30, 40, 50])

## 심화 문제 (11~20)

11. 3x3 크기의 정규 분포 난수 배열을 생성하는 코드를 작성하세요. (평균 0, 표준편차 1)
12. 3x3 배열에서 행별 합계와 열별 합계를 구하는 코드를 작성하세요.
13. 4x4 배열을 생성하고, 중앙의 2x2 부분을 슬라이싱하여 출력하세요.
14. np.array([3, 6, 9, 12, 15])에서 값이 6보다 큰 요소를 모두 -1로 바꾸세요.
15. 2x2 행렬 두 개를 생성하고, 행렬 곱셈을 수행하는 코드를 작성하세요.
16. np.array([4, 1, 7, 2, 5]) 배열을 오름차순으로 정렬하는 코드를 작성하세요.
17. np.array([1, 2, 2, 3, 3, 3, 4, 5])에서 중복을 제거하고 고유한 값만 남기세요.
18. np.array([10, 20, 30])를 2차원 배열로 변환하세요. (3x1 형태)
19. 각도 배열 [0, 30, 45, 60, 90](단위: 도)를 라디안 단위로 변환한 후 sin, cos, tan 값을 계산하세요.
20. 난수를 생성할 때 매번 같은 결과가 나오도록 하는 방법을 설명하고, 예제 코드를 작성하세요.

## Pandas
### 데이터 프레임

In [28]:
import pandas as pd
